[package]
name = "eudaemonsh"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
getopts = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rustyline = { workspace = true }

shvar = { workspace = true }
utf8path = { workspace = true }

eudaemonfs = { workspace = true }
eudaemonty = { workspace = true }
lispdown = { workspace = true }
