[package]
name = "eudaemoncli"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

claudius = { workspace = true }
utf8path = { workspace = true }

eudaemonsh = { workspace = true }
eudaemonty = { workspace = true }
