[package]
name = "eudaemonfs"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts = { workspace = true }
rustyline = { workspace = true }

guacamole = { workspace = true }
utf8path = { workspace = true }

arrrg = { workspace = true }
arrrg_derive = { workspace = true }
eudaemonty = { workspace = true }
lispdown = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[[bin]]
name = "eudaemon-fs-debug-log"
path = "src/bin/eudaemon-fs-debug-log.rs"

[[bin]]
name = "eudaemon-stress-test"
path = "src/bin/eudaemon-stress-test.rs"

[[bin]]
name = "inspect-fs"
path = "src/bin/inspect-fs.rs"
