[package]
name = "eudaemonfs"
version = "0.1.0"
edition = "2024"

[dependencies]
arrrg = "0.8.0"
arrrg_derive = "0.8.0"
eudaemonty = { path = "../eudaemonty" }
getopts = "0.2.24"
guacamole = "0.14.0"
lispdown = { path = "../lispdown" }
utf8path = "0.9.1"

[dev-dependencies]
proptest = "1.4"

[[bin]]
name = "eudaemon-fs-debug-log"
path = "src/bin/eudaemon-fs-debug-log.rs"

[[bin]]
name = "eudaemon-stress-test"
path = "src/bin/eudaemon-stress-test.rs"
