[package]
name = "lispdown"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
getopts = { workspace = true }
markdown = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

arrrg = { workspace = true }
arrrg_derive = { workspace = true }
claudius = { workspace = true }

eudaemonty = { workspace = true }
utf8path = { workspace = true }

[[example]]
name = "lincoln"
path = "examples/lincoln.rs"
